project:
  type: "website"
  title: "Adam WÄ…doÅ‚owski"
  output-dir: _output
  render:
    - "index.qmd"

format:
  html: 
    grid:
        sidebar-width: 240px
        body-width: 1100px
        margin-width: 200px
        gutter-width: 1.5rem


website:
  title: "Adam WÄ…doÅ‚owski"
  page-navigation: false
  reader-mode: false
  open-graph: true

  sidebar:
    search: false
    style: floating
    contents:
      - text: "ğŸ¡ Home"
        href: index.qmd
    tools:
      - icon: github
        text: Github
        href: https://github.com/adamwadolowski
      - icon: linkedin
        text: Linkedin
        href: https://www.linkedin.com/in/adam-wadolowski/
      - icon: envelope
        text: E-mail
        href: mailto:638726aw@student.eur.nl
    